### ISSUE TITLE
No driver registered for "file" for URL

### ISSUE THREAD

**Issue by IllyaMoskvin** [go-iiif/go-iiif-vips#1]
I'm attempting to process a few images using the `iiif-tile-seed` tool. I managed to get it working with just `go-iiif`, but I started running into memory issues, so I thought I'd try `go-iiif-vips`. I don't know if it'll solve the issue, but I thought it was worth a shot.

Unfortunately, I'm running into an error. When I run this command:
```
iiif-tile-seed \
  -refresh \
  -config-source file:///home/vagrant/www/website/bin \
  -config-name config.json \
  -endpoint https://www.artic.edu/iiif/static \
  -scale-factors 1,2,4,8,16 \
  --quality default \
  --verbose file:///dfa19a8c-293f-410d-89fb-992266c8201e
```

I get this error:

```
2020/04/22 21:21:42 open blob.Bucket: no driver registered for "file" for URL "file:///home/vagrant/www/website/bin"; available schemes: mem, s3, s3blob
```

This error only crops up when using `iiif-tile-seed` from `go-iiif-vips`. The same command appears to work fine with `go-iiif`. Any tips on where to go from here? Thanks!

**Comment by thisisaaronland** [comment]
This is a bug. Specifically the `-vips` tools are not loading the requisite `go-cloud/blob` drivers. I will fix shortly.

```
> diff -uw cmd/iiif-tile-seed/main.go ../go-iiif/cmd/iiif-tile-seed/main.go 
--- cmd/iiif-tile-seed/main.go	2020-04-22 17:28:50.000000000 -0700
+++ ../go-iiif/cmd/iiif-tile-seed/main.go	2020-04-21 09:38:57.000000000 -0700
@@ -2,8 +2,10 @@
 
 import (
 	"context"
-	_ "github.com/go-iiif/go-iiif-vips"
+	_ "github.com/aaronland/go-cloud-s3blob"
+	_ "github.com/go-iiif/go-iiif/v3/native"
 	"github.com/go-iiif/go-iiif/v3/tools"
+	_ "gocloud.dev/blob/fileblob"
 	"log"
 )
```

**Comment by thisisaaronland** [comment]
This should be fixed as `v0.2.1` or https://github.com/go-iiif/go-iiif-vips/commit/b6c48fc7f1563fa5c4b7d5be1842c4715b4d58d3

I will leave this issue open until you can confirm.

**Comment by IllyaMoskvin** [comment]
Thank you for the quick response! I can confirm that your change fixed the issue on my end.

As an aside, after switching to `go-iiif-vips`, it seems that I'm no longer running out of memory when processing large files (e.g. 118 MB, around 11000px square) the way I was with just `go-iiif`.

Thanks again!

**Comment by thisisaaronland** [comment]
@IllyaMoskvin Which version of `go-iiif` were/are you seeing these OOM problems with? Is there a public version of the image I can test against?

**Comment by IllyaMoskvin** [comment]
@thisisaaronland Ah, I just cloned the `go-iiif` repo at https://github.com/go-iiif/go-iiif/commit/b9a592255b20e5cac1d78cabce400e59bed67801 and built it locally on an old Laravel Homestead VM (Ubuntu 18.04 LTS). I can provide version numbers of any relevant installed packages, if it helps. The VM had 4096 KB of memory allocated to it.

For the image, would you mind sending me an email at imoskvin@artic.edu?

**Comment by thisisaaronland** [comment]
Will do!
